version: "3.8"

services:
  circle-postgres:
    container_name: circle-postgres
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aswassaw
      - POSTGRES_DB=circle
    networks:
      - circle-network
    ports:
      - "5444:5432"
    volumes:
      - type: volume
        source: "circle-postgres-volume"
        target: "/var/lib/postgresql/data"
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 256M
        limits:
          cpus: "0.5"
          memory: 512M

  circle-redis:
    container_name: circle-redis
    image: redis:7.2-alpine
    networks:
      - circle-network
    ports:
      - "6555:6379"
    volumes:
      - type: volume
        source: "circle-redis-volume"
        target: "/data"
    deploy:
      resources:
        reservations:
          cpus: "0.15"
          memory: 128M
        limits:
          cpus: "0.25"
          memory: 256M

  circle-rabbitmq:
    container_name: circle-rabbitmq
    image: rabbitmq:3.13.0-rc.2-management-alpine
    networks:
      - circle-network
    ports:
      - "7666:5672"
      - "14444:15672"
    volumes:
      - type: volume
        source: "circle-rabbitmq-volume"
        target: "/var/lib/rabbitmq"
    deploy:
      resources:
        reservations:
          cpus: "0.15"
          memory: 128M
        limits:
          cpus: "0.25"
          memory: 256M

networks:
  circle-network:
    name: circle-network
    driver: bridge

volumes:
  circle-postgres-volume:
    name: circle-postgres-volume
  circle-redis-volume:
    name: circle-redis-volume
  circle-rabbitmq-volume:
    name: circle-rabbitmq-volume
